from dataclasses import dataclass
from typing import Optional

'''phase params: Thinking, Tooling, Busy, Complete, Retrying, Recommend
message: The corresponding status message
Thinking -- Composing...
Tooling -- Orchestrating...
Busy -- Remixing...
Complete -- Releasing...
Retrying -- Looping...
Recommend -- Encoring...
Cleaning -- Jazzing...
Compact -- Covering... 
'''
@dataclass
class UiStatus:
    phase: str
    message: str
    tool_name: Optional[str] = None
    step: Optional[int] = None
    max_steps: Optional[int] = None