import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { SONEX_MASCOT_MICRO } from '../src/constants.js';

const appSource = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8');
const source = readFileSync(new URL('../src/components.tsx', import.meta.url), 'utf8');

const mascotStart = source.indexOf('const MiniMascotStatus =');
assert.ok(mascotStart >= 0);
const mascotEnd = source.indexOf('\n};', mascotStart);
assert.ok(mascotEnd > mascotStart);
const dynamicTailStart = source.indexOf('export const DynamicTail =');
assert.ok(dynamicTailStart > mascotStart);
const dynamicTailEnd = source.indexOf('function useVisibleSnapshotOnRevision', dynamicTailStart);
assert.ok(dynamicTailEnd > dynamicTailStart);

const mascotBody = source.slice(mascotStart, mascotEnd);
assert.match(mascotBody, /height=\{1\}/);
assert.match(mascotBody, /alignItems="flex-start"/);
assert.match(mascotBody, /paddingLeft=\{1\}/);
assert.match(mascotBody, /paddingRight=\{1\}/);
assert.match(mascotBody, /SONEX_MASCOT_MICRO\.map/);
assert.equal(mascotBody.includes('marginBottom'), false);
assert.equal(mascotBody.includes('marginTop'), false);
assert.equal(SONEX_MASCOT_MICRO.length, 1);

const dynamicTailBody = source.slice(dynamicTailStart, dynamicTailEnd);
assert.match(dynamicTailBody, /const hasModelPanel = authSetup\?\.active && authSetup\.step === "model";/);
assert.match(dynamicTailBody, /const hasSetupPanel = Boolean\(spotifySetup\) \|\| Boolean\(authSetup && authSetup\.step !== "model"\);/);
assert.match(dynamicTailBody, /const hasSlashPanel = slashSuggestions\.length > 0;/);
assert.match(dynamicTailBody, /const showInput = !helpPanel && !languagePanel && !hasModelPanel && \(!confirm \|\| Boolean\(selectedChoice\?\.input\)\);/);
assert.match(dynamicTailBody, /const showMiniMascotStatus = showInput && !confirm && !hasSlashPanel && !hasSetupPanel;/);
assert.match(dynamicTailBody, /agentWorking \? <AgentWorkingStatus \/> : <MiniMascotStatus \/>/);
assert.match(dynamicTailBody, /<InputDock[\s\S]*modelStatus=\{modelStatus\}/);
assert.equal(dynamicTailBody.includes('<MiniMascotStatus />\n        <InputDock'), false);
assert.equal(dynamicTailBody.includes('{statusText}'), false);
assert.equal(dynamicTailBody.includes('showRunMetrics'), false);
assert.equal(dynamicTailBody.includes('{elapsed}'), false);
assert.equal(dynamicTailBody.includes('{tokens}'), false);
assert.equal(appSource.includes('formatElapsed'), false);
assert.equal(appSource.includes('showRunMetrics'), false);
assert.equal(appSource.includes('setElapsed'), false);
assert.equal(appSource.includes('setTokens'), false);
assert.equal(source.includes('showRunMetrics'), false);
assert.equal(source.includes('elapsed: string | null'), false);
assert.equal(source.includes('tokens: string | null'), false);
assert.equal(source.includes('const ConversationColumn ='), false);
assert.equal(source.includes('const ConversationRegion ='), false);

const workingStart = source.indexOf('const AgentWorkingStatus =');
const workingEnd = source.indexOf('\n};', workingStart);
const workingBody = source.slice(workingStart, workingEnd);
assert.ok(workingStart > mascotStart);
assert.match(source, /const WORKING_SPINNER_FRAMES = \["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"\]/);
assert.match(source, /const WORKING_SPINNER_INTERVAL_MS = 100;/);
assert.match(workingBody, /color=\{CHAT_SYSTEM_MARKER_COLOR\}/);
assert.match(workingBody, /italic>Working/);
assert.match(workingBody, /color="#808791" bold> • Esc to interrupt/);
assert.match(appSource, /case "agent_working_state":/);
assert.match(appSource, /type:\s*"agent_turn_interrupt",\s*turn_id:\s*agentWorkingTurnId/);
