import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const app = readFileSync(new URL("../src/App.tsx", import.meta.url), "utf8");
const components = readFileSync(new URL("../src/components.tsx", import.meta.url), "utf8");

assert.match(components, /\["config memory entries", "reset memory"\]/);
assert.match(components, /\["USER\.md", "MEMORY\.md", "Memory Dump"\]/);
assert.match(components, /Review your music preferences and playback style/);
assert.match(components, /Include long-term experience and summarized notes/);
assert.match(components, /Deprecated or mistaken memory but still available for recovery/);
assert.match(components, /Sonex collects preferences and summarizes experience during your daily use\./);
assert.match(components, /↑\/↓ to select · Enter to continue · Esc to return/);
assert.match(components, /<PanelGuide width=\{width\} paddingX=\{2\} text=\{memoryFooter\} \/>/);
assert.match(components, /const descriptionColor = selected \? BORDER_BLUE : PANEL_SECONDARY;/);
assert.match(components, /bold: selected/);
assert.match(components, /panel\.view === "format"[\s\S]*\["USER\.md", "MEMORY\.md", "All memory"\]/);
assert.match(components, /const MEMORY_SETTING_LABEL_WIDTH = 48;/);
assert.match(components, /fitDisplayWidth\(label, MEMORY_SETTING_LABEL_WIDTH\)/);
assert.match(components, /formatMemorySettingRow\("Forget retention",/);
assert.doesNotMatch(components, /Disable long-term memory/);
assert.match(app, /action: "revisions"/);
assert.match(app, /action: "restore_revision"/);
assert.match(app, /mode: "setting"/);
assert.match(components, /Math\.max\(3, Math\.floor\(panelWidth\)\)/);
assert.doesNotMatch(components, /if \(activeRegion === "memoryPanel" && memoryPanel\)/);
assert.match(components, /\{memoryPanel \? \([\s\S]*<MemoryPanelOverlay/);
assert.match(components, /\{!memoryPanel \? \([\s\S]*<InputDock/);
assert.match(components, /memoryPanel=\{activeRegion === "memoryPanel" \? memoryPanel : null\}/);
assert.match(app, /planShellSurfaceTransition\(shellStateRef\.current\.region, nextRegion\)/);
assert.match(app, /surfaceForShellRegion\(shellStateRef\.current\.region\) === "main"/);
assert.match(app, /activeRegion === "chat" \|\| activeRegion === "memoryPanel" \? undefined : dynamicSurfaceHeight/);
